runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: AIC_final/index.html
  upload: AIC_final/index.html

- url: /(.*)
  static_files: AIC_final/\1
  upload: AIC_final/(.*)