runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: WebDesignProj/index.html
  upload: WebDesignProj/index.html

- url: /(.*)
  static_files: WebDesignProj/\1
  upload: WebDesignProj/(.*)